import '../models/category_model.dart';
import '../models/product_model.dart';

class MockDataService {
  static final List<CategoryModel> categories = [
    CategoryModel(id: '1', name: 'Fruits & Veggies', icon: '🍎', badgeColor: '0xFFE8F5E9'),
    CategoryModel(id: '2', name: 'Dairy & Eggs', icon: '🥛', badgeColor: '0xFFFFF8E1'),
    CategoryModel(id: '3', name: 'Meat & Seafood', icon: '🥩', badgeColor: '0xFFFFEBEE'),
    CategoryModel(id: '4', name: 'Bakery & Bread', icon: '🍞', badgeColor: '0xFFFFF3E0'),
    CategoryModel(id: '5', name: 'Beverages', icon: '🥤', badgeColor: '0xFFE0F7FA'),
    CategoryModel(id: '6', name: 'Snacks & Munchies', icon: '🍿', badgeColor: '0xFFF3E5F5'),
    CategoryModel(id: '7', name: 'Frozen Foods', icon: '🧊', badgeColor: '0xFFE1F5FE'),
    CategoryModel(id: '8', name: 'Pantry Staples', icon: '🌾', badgeColor: '0xFFEFEBE9'),
    CategoryModel(id: '9', name: 'Household Needs', icon: '🧹', badgeColor: '0xFFECEFF1'),
    CategoryModel(id: '10', name: 'Personal Care', icon: '🧴', badgeColor: '0xFFFCE4EC'),
  ];

  static final List<ProductModel> products = [
    // Fruits & Veggies
    ProductModel(
      id: 'p1',
      name: 'Organic Bananas',
      categoryId: '1',
      price: 1.99,
      unit: '1 Bunch (~3 lbs)',
      imageEmoji: '🍌',
      imageUrl: 'https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=500&auto=format&fit=crop',
      badgeText: 'ORGANIC',
    ),
    ProductModel(
      id: 'p2',
      name: 'Fresh Hass Avocados',
      categoryId: '1',
      price: 3.99,
      comparePrice: 4.99,
      unit: '4 Pack Bag',
      imageEmoji: '🥑',
      imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=500&auto=format&fit=crop',
      badgeText: 'BESTSELLER',
    ),
    ProductModel(
      id: 'p3',
      name: 'Fresh Strawberries',
      categoryId: '1',
      price: 4.49,
      comparePrice: 5.49,
      unit: '16 oz Container',
      imageEmoji: '🍓',
      imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=500&auto=format&fit=crop',
      badgeText: '18% OFF',
    ),
    ProductModel(
      id: 'p4',
      name: 'Honeycrisp Apples',
      categoryId: '1',
      price: 2.99,
      unit: '2 lbs Bag',
      imageEmoji: '🍎',
      imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=500&auto=format&fit=crop',
    ),
    ProductModel(
      id: 'p5',
      name: 'Fresh Organic Baby Spinach',
      categoryId: '1',
      price: 3.29,
      unit: '5 oz Tub',
      imageEmoji: '🥬',
      imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&auto=format&fit=crop',
      badgeText: 'FRESH',
    ),
    ProductModel(
      id: 'p6',
      name: 'Sweet Cherry Tomatoes',
      categoryId: '1',
      price: 2.79,
      unit: '10 oz Pack',
      imageEmoji: '🍅',
      imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop',
    ),

    // Dairy & Eggs
    ProductModel(
      id: 'p7',
      name: 'Organic Whole Milk',
      categoryId: '2',
      price: 5.99,
      comparePrice: 6.99,
      unit: '1 Gallon',
      imageEmoji: '🥛',
      imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&auto=format&fit=crop',
      badgeText: '15% OFF',
    ),
    ProductModel(
      id: 'p8',
      name: 'Large Grade A Brown Eggs',
      categoryId: '2',
      price: 4.29,
      comparePrice: 4.99,
      unit: '12 Count Cartons',
      imageEmoji: '🥚',
      imageUrl: 'https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?w=500&auto=format&fit=crop',
      badgeText: 'TOP RATED',
    ),
    ProductModel(
      id: 'p9',
      name: 'Greek Plain Yogurt Tub',
      categoryId: '2',
      price: 5.49,
      unit: '32 oz Tub',
      imageEmoji: '🥣',
      imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&auto=format&fit=crop',
    ),
    ProductModel(
      id: 'p10',
      name: 'Unsalted Sweet Butter',
      categoryId: '2',
      price: 3.99,
      unit: '16 oz (4 Sticks)',
      imageEmoji: '🧈',
      imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=500&auto=format&fit=crop',
    ),
    ProductModel(
      id: 'p11',
      name: 'Shredded Sharp Cheddar',
      categoryId: '2',
      price: 3.79,
      unit: '8 oz Bag',
      imageEmoji: '🧀',
      imageUrl: 'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?w=500&auto=format&fit=crop',
    ),

    // Meat & Seafood
    ProductModel(
      id: 'p12',
      name: 'Fresh Atlantic Salmon Fillet',
      categoryId: '3',
      price: 12.99,
      comparePrice: 14.99,
      unit: '1 lb Portion',
      imageEmoji: '🍣',
      imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=500&auto=format&fit=crop',
      badgeText: 'WILD CAUGHT',
    ),
    ProductModel(
      id: 'p13',
      name: 'Grass-Fed Ground Beef 85/15',
      categoryId: '3',
      price: 7.99,
      unit: '1 lb Pack',
      imageEmoji: '🥩',
      imageUrl: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=500&auto=format&fit=crop',
    ),
    ProductModel(
      id: 'p14',
      name: 'Boneless Chicken Breast',
      categoryId: '3',
      price: 6.49,
      unit: '1.5 lbs Tray',
      imageEmoji: '🍗',
      imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=500&auto=format&fit=crop',
    ),

    // Bakery
    ProductModel(
      id: 'p15',
      name: 'Artisan Whole Wheat Bread',
      categoryId: '4',
      price: 3.49,
      unit: '20 oz Loaf',
      imageEmoji: '🍞',
      imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop',
    ),
    ProductModel(
      id: 'p16',
      name: 'Fresh Butter Croissants',
      categoryId: '4',
      price: 4.99,
      unit: '4 Pack',
      imageEmoji: '🥐',
      imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=500&auto=format&fit=crop',
      badgeText: 'BAKED TODAY',
    ),

    // Beverages
    ProductModel(
      id: 'p17',
      name: '100% Pure Orange Juice',
      categoryId: '5',
      price: 4.99,
      unit: '52 fl oz Bottle',
      imageEmoji: '🧃',
      imageUrl: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=500&auto=format&fit=crop',
    ),
    ProductModel(
      id: 'p18',
      name: 'Sparkling Mineral Water',
      categoryId: '5',
      price: 6.99,
      unit: '12 Pack Cans',
      imageEmoji: '🥤',
      imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=500&auto=format&fit=crop',
    ),

    // Snacks
    ProductModel(
      id: 'p19',
      name: 'Organic Sea Salt Tortilla Chips',
      categoryId: '6',
      price: 3.79,
      unit: '10 oz Bag',
      imageEmoji: '🍿',
      imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop',
    ),
    ProductModel(
      id: 'p20',
      name: 'Vanilla Bean Ice Cream',
      categoryId: '7',
      price: 4.99,
      unit: '1 Pint',
      imageEmoji: '🍨',
      imageUrl: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=500&auto=format&fit=crop',
    ),

    // Pantry
    ProductModel(
      id: 'p21',
      name: 'Extra Virgin Olive Oil',
      categoryId: '8',
      price: 9.99,
      comparePrice: 11.99,
      unit: '16.9 fl oz',
      imageEmoji: '🫒',
      imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop',
      badgeText: 'IMPORTED',
    ),
  ];
}
